feat: tests of version getter
dil-classroom/projet-friedli_jaquier_kaelin_pavicevic pull request #74
Opened 2022-06-02 10:34 UTC by AJaquier

2022-06-09 20:59 UTC, vkaelin requested changes
Looks better good job!

Maybe take a look at the proposed changes (to remove magic numbers and some variable names).

You'll need to check if the tests pass and if you need to re-apply spotless if you accept my changes.

2022-06-09 20:59 UTC, vkaelin commented on src/test/java/ch/heig/dil/BoomshotTest.java
> +        assertEquals(version[1], testVers);
```suggestion
        final String OPEN_TAG = "<version>";
        final String CLOSING_TAG = "</version>";
        Boomshot.VersionProvide versionProvide = new Boomshot.VersionProvide();
        String pomContent = FilesHelper.readFromFile("pom.xml");
        assertTrue(pomContent != null);
        String configVersion =
                pomContent.substring(
                        pomContent.indexOf(OPEN_TAG) + OPEN_TAG.length(), pomContent.indexOf(CLOSING_TAG));
        String[] rawVersion = versionProvide.getVersion();
        String[] generatedVersion = rawVersion[0].split(" ");
        assertEquals(generatedVersion[0], "Boomshot");

        assertEquals(generatedVersion[1], configVersion);
```

2022-06-10 20:06 UTC, vkaelin commented on src/test/java/ch/heig/dil/BoomshotTest.java
> +        assertEquals(version[1], configVersion);
```suggestion
        final String OPEN_TAG = "<version>";
        final String CLOSING_TAG = "</version>";
        Boomshot.VersionProvide versionProvide = new Boomshot.VersionProvide();
        String pomContent = FilesHelper.readFromFile("pom.xml");
        String configVersion =
                pomContent.substring(
                        pomContent.indexOf(OPEN_TAG) + OPEN_TAG.length(),
                        pomContent.indexOf(CLOSING_TAG));
        String[] rawVersion = versionProvide.getVersion();
        String[] generatedVersion = rawVersion[0].split(" ");
        assertEquals(version[0], "Boomshot");

        assertEquals(generatedVersion[1], configVersion);
```

2022-06-10 20:14 UTC, AJaquier commented on src/test/java/ch/heig/dil/BoomshotTest.java
> +        assertEquals(version[0], "Boomshot");
```suggestion
        assertEquals(generatedVersion[0], "Boomshot");
```

2022-06-10 20:29 UTC, vkaelin approved these changes
LGTM now !

2022-06-10 20:29 UTC, merged